//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZurbFoundationEcommerce.Modules {
    
    
    public partial class TopProducts {
        
        /// <summary>
        /// ProductCardMini2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Modules.ProductCardMini2 ProductCardMini2;
        
        /// <summary>
        /// ProductCardMini1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Modules.ProductCardMini2 ProductCardMini1;
        
        /// <summary>
        /// ProductCardMini3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Modules.ProductCardMini2 ProductCardMini3;
        
        /// <summary>
        /// ProductCardMini4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Modules.ProductCardMini2 ProductCardMini4;
        
        /// <summary>
        /// ProductCardMini5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Modules.ProductCardMini2 ProductCardMini5;
        
        /// <summary>
        /// ProductCardMini6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Modules.ProductCardMini2 ProductCardMini6;
    }
}
