//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZurbFoundationEcommerce.Administration {
    
    
    public partial class _default {
        
        /// <summary>
        /// CallOutStat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.CallOutStat CallOutStat;
        
        /// <summary>
        /// CallOutStat1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.CallOutStat CallOutStat1;
        
        /// <summary>
        /// CallOutStat2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.CallOutStat CallOutStat2;
        
        /// <summary>
        /// CallOutStat3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.CallOutStat CallOutStat3;
        
        /// <summary>
        /// ChartCard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.ChartCard ChartCard;
        
        /// <summary>
        /// ChartCard1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.ChartCard ChartCard1;
        
        /// <summary>
        /// CallOutLargeValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.CallOutLargeValue CallOutLargeValue;
        
        /// <summary>
        /// CallOutLargeValue1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.CallOutLargeValue CallOutLargeValue1;
        
        /// <summary>
        /// CallOutLargeValue2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.CallOutLargeValue CallOutLargeValue2;
        
        /// <summary>
        /// TablePendingOrders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.TablePendingOrders TablePendingOrders;
        
        /// <summary>
        /// ChartCard2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.ChartCard ChartCard2;
        
        /// <summary>
        /// TableSalesByProduct control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Administration.Modules.TableSalesByProduct TableSalesByProduct;
    }
}
