//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZurbFoundationEcommerce {
    
    
    public partial class view {
        
        /// <summary>
        /// ProductReview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Modules.ProductReview ProductReview;
        
        /// <summary>
        /// ProductReview1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Modules.ProductReview ProductReview1;
        
        /// <summary>
        /// ProductReview2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ZurbFoundationEcommerce.Modules.ProductReview ProductReview2;
    }
}
